DROP TABLE MYMEMBER;
DROP SEQUENCE MYNOSEQ;

CREATE SEQUENCE MYNOSEQ NOCACHE;
--맴버번호, 아이디, 비밀번호, 이름, 주소, 전화번호, 이메일, 가입여부(가입/탈퇴), 등급(ADMIN/USER, ...)
CREATE TABLE MYMEMBER(
	MYNO NUMBER NOT NULL,
	MYID VARCHAR2(500) NOT NULL,
	MYPW VARCHAR2(500) NOT NULL,
	MYNAME VARCHAR2(1000) NOT NULL,
	MYADDR VARCHAR2(4000) NOT NULL,
	MYPHONE VARCHAR2(20) NOT NULL,
	MYEMAIL VARCHAR2(100) NOT NULL,
	MYENABLED VARCHAR2(2) NOT NULL,
	MYROLE VARCHAR2(50) NOT NULL,
	CONSTRAINT MEMBER_PK PRIMARY KEY(MYNO),
	CONSTRAINT MEMBER_UQ_ID UNIQUE(MYID),
	CONSTRAINT MEMBER_UQ_EMAIL UNIQUE(MYEMAIL),
	CONSTRAINT MEMBER_UQ_PHONE UNIQUE(MYPHONE),
	CONSTRAINT MEMBER_ENABLED_CHK CHECK(MYENABLED IN('Y','N') )
);

INSERT INTO MYMEMBER VALUES(
MYNOSEQ.NEXTVAL,'ADMIN','ADMIN1234','관리자','관리시 관리구 관리동','010-1234-5678'
,'ADMIN@MYMEMBER.COM','Y','ADMIN');

INSERT INTO MYMEMBER VALUES(
MYNOSEQ.NEXTVAL,'USER1','USER1','이창진','서울시 강남구 역삼동','010-2222-2233'
,'USER1@MYMEMBER.COM','Y','USER');

INSERT INTO MYMEMBER VALUES(
MYNOSEQ.NEXTVAL,'USER2','USER2','홍길동','경기도 수원시 권선구','010-3333-1234'
,'USER2@MYMEMBER.COM','N','USER');


SELECT * FROM MYMEMBER;