SELECT * FROM EMP;
SELECT * FROM EMPLOYEE;
-- 실행 블럭 후 ALT +X

DROP TABLE MYTEST;
--테이블이 있는지 모르니까 일단 지우고 시작
CREATE TABLE MYTEST(
		MNO NUMBER(10),
		MNAME VARCHAR2(20),
		NICKNAME VARCHAR2(20)
);
SELECT * FROM MYTEST;
